//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.25 at 12:58:02 PM CEST 
//


package com.ccl.documentmanagementintapi.domain.ws.anubisabastdocument;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ccl.documentmanagementintapi.domain.ws.anubisabastdocument package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestUpload_QNAME = new QName("http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", "RequestUpload");
    private final static QName _RequestDownload_QNAME = new QName("http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", "RequestDownload");
    private final static QName _RequestDelete_QNAME = new QName("http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", "RequestDelete");
    private final static QName _Response_QNAME = new QName("http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ccl.documentmanagementintapi.domain.ws.anubisabastdocument
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestUploadType }
     * 
     */
    public RequestUploadType createRequestUploadType() {
        return new RequestUploadType();
    }

    /**
     * Create an instance of {@link RequestDownloadType }
     * 
     */
    public RequestDownloadType createRequestDownloadType() {
        return new RequestDownloadType();
    }

    /**
     * Create an instance of {@link RequestDeleteType }
     * 
     */
    public RequestDeleteType createRequestDeleteType() {
        return new RequestDeleteType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestUploadType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestUploadType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", name = "RequestUpload")
    public JAXBElement<RequestUploadType> createRequestUpload(RequestUploadType value) {
        return new JAXBElement<RequestUploadType>(_RequestUpload_QNAME, RequestUploadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDownloadType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestDownloadType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", name = "RequestDownload")
    public JAXBElement<RequestDownloadType> createRequestDownload(RequestDownloadType value) {
        return new JAXBElement<RequestDownloadType>(_RequestDownload_QNAME, RequestDownloadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDeleteType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestDeleteType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", name = "RequestDelete")
    public JAXBElement<RequestDeleteType> createRequestDelete(RequestDeleteType value) {
        return new JAXBElement<RequestDeleteType>(_RequestDelete_QNAME, RequestDeleteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", name = "Response")
    public JAXBElement<ResponseType> createResponse(ResponseType value) {
        return new JAXBElement<ResponseType>(_Response_QNAME, ResponseType.class, null, value);
    }

}
