//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.25 at 12:58:02 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.transfesa.com/api_anubis_document/AnubisAbastDocument", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ccl.documentmanagementintapi.domain.ws.anubisabastdocument;
