//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.25 at 12:58:02 PM CEST 
//


package com.ccl.documentmanagementintapi.domain.ws.anubisabastdocument;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for RequestUploadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestUploadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaDocMilis" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="categoria" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idocPadre" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="usuario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rolUsuario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="localizador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numeroDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nombreFichero" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="binario" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "RequestUpload")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestUploadType", propOrder = {
    "titulo",
    "descripcion",
    "fechaDocMilis",
    "categoria",
    "idocPadre",
    "usuario",
    "rolUsuario",
    "localizador",
    "cliente",
    "numeroDocumento",
    "nombreFichero",
    "binario"
})
public class RequestUploadType
    implements ToString
{

    @XmlElement(required = true)
    protected String titulo;
    @XmlElement(required = true)
    protected String descripcion;
    protected long fechaDocMilis;
    @XmlElement(required = true)
    protected String categoria;
    protected int idocPadre;
    @XmlElement(required = true)
    protected String usuario;
    @XmlElement(required = true)
    protected String rolUsuario;
    @XmlElement(required = true)
    protected String localizador;
    protected String cliente;
    protected String numeroDocumento;
    @XmlElement(required = true)
    protected String nombreFichero;
    @XmlElement(required = true)
    protected byte[] binario;

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the fechaDocMilis property.
     * 
     */
    public long getFechaDocMilis() {
        return fechaDocMilis;
    }

    /**
     * Sets the value of the fechaDocMilis property.
     * 
     */
    public void setFechaDocMilis(long value) {
        this.fechaDocMilis = value;
    }

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    /**
     * Gets the value of the idocPadre property.
     * 
     */
    public int getIdocPadre() {
        return idocPadre;
    }

    /**
     * Sets the value of the idocPadre property.
     * 
     */
    public void setIdocPadre(int value) {
        this.idocPadre = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the rolUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolUsuario() {
        return rolUsuario;
    }

    /**
     * Sets the value of the rolUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolUsuario(String value) {
        this.rolUsuario = value;
    }

    /**
     * Gets the value of the localizador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalizador() {
        return localizador;
    }

    /**
     * Sets the value of the localizador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalizador(String value) {
        this.localizador = value;
    }

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCliente(String value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the numeroDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroDocumento() {
        return numeroDocumento;
    }

    /**
     * Sets the value of the numeroDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroDocumento(String value) {
        this.numeroDocumento = value;
    }

    /**
     * Gets the value of the nombreFichero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreFichero() {
        return nombreFichero;
    }

    /**
     * Sets the value of the nombreFichero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreFichero(String value) {
        this.nombreFichero = value;
    }

    /**
     * Gets the value of the binario property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBinario() {
        return binario;
    }

    /**
     * Sets the value of the binario property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBinario(byte[] value) {
        this.binario = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theTitulo;
            theTitulo = this.getTitulo();
            strategy.appendField(locator, this, "titulo", buffer, theTitulo);
        }
        {
            String theDescripcion;
            theDescripcion = this.getDescripcion();
            strategy.appendField(locator, this, "descripcion", buffer, theDescripcion);
        }
        {
            long theFechaDocMilis;
            theFechaDocMilis = (true?this.getFechaDocMilis(): 0L);
            strategy.appendField(locator, this, "fechaDocMilis", buffer, theFechaDocMilis);
        }
        {
            String theCategoria;
            theCategoria = this.getCategoria();
            strategy.appendField(locator, this, "categoria", buffer, theCategoria);
        }
        {
            int theIdocPadre;
            theIdocPadre = (true?this.getIdocPadre(): 0);
            strategy.appendField(locator, this, "idocPadre", buffer, theIdocPadre);
        }
        {
            String theUsuario;
            theUsuario = this.getUsuario();
            strategy.appendField(locator, this, "usuario", buffer, theUsuario);
        }
        {
            String theRolUsuario;
            theRolUsuario = this.getRolUsuario();
            strategy.appendField(locator, this, "rolUsuario", buffer, theRolUsuario);
        }
        {
            String theLocalizador;
            theLocalizador = this.getLocalizador();
            strategy.appendField(locator, this, "localizador", buffer, theLocalizador);
        }
        {
            String theCliente;
            theCliente = this.getCliente();
            strategy.appendField(locator, this, "cliente", buffer, theCliente);
        }
        {
            String theNumeroDocumento;
            theNumeroDocumento = this.getNumeroDocumento();
            strategy.appendField(locator, this, "numeroDocumento", buffer, theNumeroDocumento);
        }
        {
            String theNombreFichero;
            theNombreFichero = this.getNombreFichero();
            strategy.appendField(locator, this, "nombreFichero", buffer, theNombreFichero);
        }
        {
            byte[] theBinario;
            theBinario = this.getBinario();
            strategy.appendField(locator, this, "binario", buffer, theBinario);
        }
        return buffer;
    }

}
